# Generated by Django 4.2.5 on 2023-09-24 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copywriting', '0005_alter_profile_openai_api_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
