# Generated by Django 4.2.5 on 2023-09-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copywriting', '0006_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promt_items', models.TextField(verbose_name='Промт для получения списка статей')),
                ('promt_article', models.TextField(default={}, verbose_name='Промт для получения текста')),
            ],
            options={
                'verbose_name': 'Конфигурация',
                'verbose_name_plural': 'Конфигурации',
            },
        ),
    ]
