# Generated by Django 4.2.5 on 2023-09-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copywriting', '0007_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='promt_items',
            field=models.TextField(default=[], verbose_name='Промт для получения списка статей'),
        ),
    ]
