# Generated by Django 4.2.5 on 2023-09-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copywriting', '0009_alter_config_options_alter_config_promt_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.TextField(default='{}', verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='structure',
            field=models.TextField(default='[]', verbose_name='Содержание'),
        ),
    ]
