# Generated by Django 4.2.5 on 2023-09-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='openai_api_key',
            field=models.TextField(default='', max_length=100, verbose_name='openai_api_key'),
        ),
    ]
