# Generated by Django 4.2.5 on 2023-09-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_profile_openai_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='openai_api_key',
            field=models.CharField(blank=True, default=None, max_length=40, verbose_name='openai_api_key'),
        ),
    ]
