# Generated by Django 4.2.5 on 2023-09-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_profile_openai_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='openai_api_key',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='OPENAI API KEY'),
        ),
    ]
